# Generated by Django 3.2.21 on 2023-09-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeranking', '0003_title_media_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranimeranking',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='useranimeranking',
            name='user',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='title',
            name='media_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='UserAnimeRanking',
        ),
    ]
