# Generated by Django 3.2.21 on 2023-11-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeranking', '0007_auto_20231023_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnimeList',
            new_name='UserAnime',
        ),
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='UserBookmarks',
        ),
    ]
