# Generated by Django 3.2.21 on 2023-11-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeranking', '0008_auto_20231101_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='ranking',
            field=models.FloatField(),
        ),
    ]
