# Generated by Django 5.0.3 on 2024-03-28 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('popularity', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.ManyToManyField(to='jaku.genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaku.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaku.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.FloatField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaku.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaku.userprofile')),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
